CrazyMonitor/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from monitor import views
from monitor import api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/',include('monitor.api_urls')),
    url(r'^$',views.dashboard,name='dashboard' ),
    url(r'^monitor/',include('monitor.urls')),

]

monitor/urls.py
from django.conf.urls import url

from  monitor import views

urlpatterns = [

    #url(r'^$',views.dashboard ),
    #url(r'^dashboard/$',views.dashboard ,name='dashboard' ),
    url(r'^triggers/$',views.triggers,name='triggers' ),
    url(r'hosts/$',views.hosts ,name='hosts'),
    url(r'host_groups/$',views.host_groups ,name='host_groups'),
    url(r'hosts/(\d+)/$',views.host_detail ,name='host_detail'),
    #url(r'graph/$',views.graph ,name='get_graph'),
    url(r'trigger_list/$',views.trigger_list ,name='trigger_list'),
    #url(r'client/service/report/$',views.service_data_report )

]

monitor/models.py
from django.db import models
from monitor import auth
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe

# Create your models here.




class Host(models.Model):
    name =  models.CharField(max_length=64,unique=True)
    ip_addr =  models.GenericIPAddressField(unique=True)
    host_groups = models.ManyToManyField('HostGroup',blank=True) # A B C
    templates = models.ManyToManyField("Template",blank=True) # A D E
    monitored_by_choices = (
        ('agent','Agent'),
        ('snmp','SNMP'),
        ('wget','WGET'),
    )
    monitored_by = models.CharField(u'监控方式',max_length=64,choices=monitored_by_choices)
    status_choices= (
        (1,'Online'),
        (2,'Down'),
        (3,'Unreachable'),
        (4,'Offline'),
        (5,'Problem'),
    )
    host_alive_check_interval = models.IntegerField(u"主机存活状态检测间隔", default=30)
    status = models.IntegerField(u'状态',choices=status_choices,default=1)
    memo = models.TextField(u"备注",blank=True,null=True)

    def __str__(self):
        return self.name

class HostGroup(models.Model):
    name = models.CharField(max_length=64,unique=True)
    templates = models.ManyToManyField("Template",blank=True)
    memo = models.TextField(u"备注",blank=True,null=True)

    def __str__(self):
        return self.name

class ServiceIndex(models.Model):
    name = models.CharField(max_length=64)
    key =models.CharField(max_length=64)
    data_type_choices = (
        ('int',"int"),
        ('float',"float"),
        ('str',"string")
    )
    data_type = models.CharField(u'指标数据类型',max_length=32,choices=data_type_choices,default='int')
    memo = models.CharField(u"备注",max_length=128,blank=True,null=True)

    def __str__(self):
        return "%s.%s" %(self.name,self.key)

class Service(models.Model):
    name = models.CharField(u'服务名称',max_length=64,unique=True)
    interval = models.IntegerField(u'监控间隔',default=60)
    plugin_name = models.CharField(u'插件名',max_length=64,default='n/a')
    items = models.ManyToManyField('ServiceIndex',verbose_name=u"指标列表",blank=True)
    has_sub_service = models.BooleanField(default=False,help_text=u"如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡") #如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡
    memo = models.CharField(u"备注",max_length=128,blank=True,null=True)

    def __str__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(u'模版名称',max_length=64,unique=True)
    services = models.ManyToManyField('Service',verbose_name=u"服务列表")
    triggers = models.ManyToManyField('Trigger',verbose_name=u"触发器列表",blank=True)

    def __str__(self):
        return self.name


class TriggerExpression(models.Model):
    trigger = models.ForeignKey('Trigger',verbose_name=u"所属触发器")
    service = models.ForeignKey(Service,verbose_name=u"关联服务")
    service_index = models.ForeignKey(ServiceIndex,verbose_name=u"关联服务指标")
    specified_index_key = models.CharField(verbose_name=u"只监控专门指定的指标key",max_length=64,blank=True,null=True)
    operator_type_choices = (('eq','='),('lt','<'),('gt','>'))
    operator_type = models.CharField(u"运算符",choices=operator_type_choices,max_length=32)
    data_calc_type_choices = (
        ('avg','Average'),
        ('max','Max'),
        ('hit','Hit'),
        ('last','Last'),
    )
    data_calc_func= models.CharField(u"数据处理方式",choices=data_calc_type_choices,max_length=64)
    data_calc_args = models.CharField(u"函数传入参数",help_text=u"若是多个参数,则用,号分开,第一个值是时间",max_length=64)
    threshold = models.IntegerField(u"阈值")
    logic_type_choices = (('or','OR'),('and','AND'))
    logic_type = models.CharField(u"与一个条件的逻辑关系",choices=logic_type_choices,max_length=32,blank=True,null=True)

    def __str__(self):
        return "%s %s(%s(%s))" %(self.service_index,self.operator_type,self.data_calc_func,self.data_calc_args)


class Trigger(models.Model):
    name = models.CharField(u'触发器名称',max_length=64)
    severity_choices = (
        (1,'Information'),
        (2,'Warning'),
        (3,'Average'),
        (4,'High'),
        (5,'Diaster'),
    )
    #expressions = models.ManyToManyField(TriggerExpression,verbose_name=u"条件表达式")
    severity = models.IntegerField(u'告警级别',choices=severity_choices)
    enabled = models.BooleanField(default=True)
    memo = models.TextField(u"备注",blank=True,null=True)

    def __str__(self):
        return "<serice:%s, severity:%s>" %(self.name,self.get_severity_display())


class Action(models.Model):
    """定义trigger发生后，如何报警"""
    name = models.CharField(max_length=64,unique=True)
    host_groups = models.ManyToManyField('HostGroup',blank=True) #在template里已经关联了主机和tirgger了，为什么这里还要有
    hosts = models.ManyToManyField('Host',blank=True)
    triggers = models.ManyToManyField('Trigger',blank=True,help_text=u"想让哪些trigger触发当前报警动作")
    interval = models.IntegerField(u'告警间隔(s)',default=300)
    operations = models.ManyToManyField('ActionOperation')
    recover_notice = models.BooleanField(u'故障恢复后发送通知消息',default=True)
    recover_subject = models.CharField(max_length=128,blank=True,null=True)
    recover_message = models.TextField(blank=True,null=True)

    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ActionOperation(models.Model):
    """报警动作列表"""
    name = models.CharField(max_length=64)
    step = models.SmallIntegerField(u"第n次告警",default=1,help_text="当trigger触发次数小于这个值时就执行这条记录里报警方式")
    action_type_choices = (
        ('email','Email'),
        ('sms','SMS'),
        ('script','RunScript'),
    )
    action_type = models.CharField(u"动作类型",choices=action_type_choices,default='email',max_length=64)
    notifiers= models.ManyToManyField('UserProfile',verbose_name=u"通知对象",blank=True)
    _msg_format = '''Host({hostname},{ip}) service({service_name}) has issue,msg:{msg}'''

    msg_format = models.TextField(u"消息格式",default=_msg_format)
    def __str__(self):
        return self.name


class Maintenance(models.Model):
    name =  models.CharField(max_length=64,unique=True)
    hosts = models.ManyToManyField('Host',blank=True)
    host_groups = models.ManyToManyField('HostGroup',blank=True)
    content = models.TextField(u"维护内容")
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return self.name


class EventLog(models.Model):
    """存储报警及其它事件日志"""
    event_type_choices = ((0,'报警事件'),(1,'维护事件'))
    event_type = models.SmallIntegerField(choices=event_type_choices,default=0)
    host = models.ForeignKey("Host")
    trigger = models.ForeignKey("Trigger",blank=True,null=True)
    log = models.TextField(blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return "host%s  %s" %(self.host , self.log)

class UserProfile(auth.AbstractBaseUser, auth.PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,

    )
    password = models.CharField(_('password'), max_length=128,
                                help_text=mark_safe('''<a class='btn-link' href='password'>重置密码</a>'''))
    phone = models.BigIntegerField(blank=True,null=True)
    weixin = models.CharField(max_length=64,blank=True,null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=True,
        help_text='Designates whether the user can log into this admin site.',
    )
    name = models.CharField(max_length=32)
    #role = models.ForeignKey("Role",verbose_name="权限角色")

    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['name','token','department','tel','mobile','memo']
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __str__ on Python 2
        return self.email

    def has_perms(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True


    @property
    def is_superuser(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


    objects = auth.UserManager()

    class Meta:
        verbose_name = '账户'
        verbose_name_plural = '账户'






''''
CPU
    idle 80
    usage  90
    system  30
    user
    iowait  50

memory :
    usage
    free
    swap
    cache
    buffer

load:
    load1
    load 5
    load 15
'''

monitor/views.py
#_*_coding:utf8_*_
from django.shortcuts import render,HttpResponse
from django.views.decorators.csrf import csrf_exempt

from  CrazyMonitor import settings
import json,time
# Create your views here.
from  monitor.serializer import  ClientHandler,get_host_triggers
import json
from monitor.backends import redis_conn
from monitor.backends import data_optimization
from monitor import models
from monitor.backends import data_processing
from monitor import serializer
from monitor import graphs




REDIS_OBJ = redis_conn.redis_conn(settings)

def dashboard(request):

    return render(request,'monitor/dashboard.html')

def triggers(request):

    return render(request,'monitor/triggers.html')


def hosts(request):
    host_list = models.Host.objects.all()
    print("hosts:",host_list)
    return render(request,'monitor/hosts.html',{'host_list':host_list})

def host_detail(request,host_id):
    host_obj = models.Host.objects.get(id=host_id)
    return render(request,'monitor/host_detail.html',{'host_obj':host_obj})

def host_detail_old(request,host_id):
    host_obj = models.Host.objects.get(id=host_id)

    config_obj = ClientHandler(host_obj.id)
    monitored_services = {
            "services":{},
            "sub_services": {} #存储一个服务有好几个独立子服务 的监控,比如网卡服务 有好几个网卡
        }

    template_list= list(host_obj.templates.select_related())

    for host_group in host_obj.host_groups.select_related():
        template_list.extend( host_group.templates.select_related() )
    print(template_list)
    for template in template_list:
        #print(template.services.select_related())

        for service in template.services.select_related(): #loop each service
            print(service)
            if not service.has_sub_service:
                monitored_services['services'][service.name] = [service.plugin_name,service.interval]
            else:
                monitored_services['sub_services'][service.name] = []

                #get last point from redis in order to acquire the sub-service-key
                last_data_point_key = "StatusData_%s_%s_latest" %(host_obj.id,service.name)
                last_point_from_redis = REDIS_OBJ.lrange(last_data_point_key,-1,-1)[0]
                if last_point_from_redis:
                    data,data_save_time = json.loads(last_point_from_redis)
                    if data:
                        service_data_dic = data.get('data')
                        for serivce_key,val in service_data_dic.items():
                            monitored_services['sub_services'][service.name].append(serivce_key)


    return render(request,'host_detail.html', {'host_obj':host_obj,'monitored_services':monitored_services})


def hosts_status(request):

    hosts_data_serializer = serializer.StatusSerializer(request,REDIS_OBJ)
    hosts_data = hosts_data_serializer.by_hosts()

    return HttpResponse(json.dumps(hosts_data))


def hostgroups_status(request):
    group_serializer = serializer.GroupStatusSerializer(request,REDIS_OBJ)
    group_serializer.get_all_groups_status()

    return HttpResponse('ss')


def client_configs(request,client_id):
    print("--->",client_id)
    config_obj = ClientHandler(client_id)
    config = config_obj.fetch_configs()

    if config:
        return HttpResponse(json.dumps(config))

@csrf_exempt
def service_data_report(request):
    if request.method == 'POST':
        print("---->",request.POST)
        #REDIS_OBJ.set("test_alex",'hahaha')
        try:
            print('host=%s, service=%s' %(request.POST.get('client_id'),request.POST.get('service_name') ) )
            data =  json.loads(request.POST['data'])
            #print(data)
            #StatusData_1_memory_latest
            client_id = request.POST.get('client_id')
            service_name = request.POST.get('service_name')
            #把数据存下来
            data_saveing_obj = data_optimization.DataStore(client_id,service_name,data,REDIS_OBJ)

            #redis_key_format = "StatusData_%s_%s_latest" %(client_id,service_name)
            #data['report_time'] = time.time()
            #REDIS_OBJ.lpush(redis_key_format,json.dumps(data))

            #在这里同时触发监控(在这里触发的好处是什么呢？)
            host_obj = models.Host.objects.get(id=client_id)
            service_triggers = get_host_triggers(host_obj)

            trigger_handler = data_processing.DataHandler(settings,connect_redis=False)
            for trigger in service_triggers:
                trigger_handler.load_service_data_and_calulating(host_obj,trigger,REDIS_OBJ)
            print("service trigger::",service_triggers)


            #更新主机存活状态
            #host_alive_key = "HostAliveFlag_%s" % client_id
            #REDIS_OBJ.set(host_alive_key,time.time())
        except IndexError as e:
            print('----->err:',e)


    return HttpResponse(json.dumps("---report success---"))


def graphs_generator(request):

    graphs_generator = graphs.GraphGenerator2(request,REDIS_OBJ)
    graphs_data = graphs_generator.get_host_graph()
    print("graphs_data",graphs_data)
    return HttpResponse(json.dumps(graphs_data))

def graph_bak(request):


    #host_id = request.GET.get('host_id')
    #service_key = request.GET.get('service_key')

    #print("graph:", host_id,service_key)

    graph_generator = graphs.GraphGenerator(request,REDIS_OBJ)
    graph_data = graph_generator.get_graph_data()
    if graph_data:
        return HttpResponse(json.dumps(graph_data))


def trigger_list(request):

    host_id = request.GET.get("by_host_id")

    host_obj = models.Host.objects.get(id=host_id)

    alert_list = host_obj.eventlog_set.all().order_by('-date')
    return render(request,'monitor/trigger_list.html',locals())


def host_groups(request):

    host_groups = models.HostGroup.objects.all()
    return render(request,'monitor/host_groups.html',locals())

templates/monitor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>CrazyMonitor | Oldboy edu </title>


	<!--STYLESHEET-->
	<!--=================================================-->

	<!--Bootstrap Stylesheet [ REQUIRED ]-->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">


	<!--Nifty Stylesheet [ REQUIRED ]-->
	<link href="/static/css/nifty.min.css" rel="stylesheet">


	<!--Font Awesome [ OPTIONAL ]-->
	<link href="/static/css/font-awesome.min.css" rel="stylesheet">
	<link href="/static/css/custom.css" rel="stylesheet">


	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.


	Detailed information and more samples can be found in the document.

	-->


</head>

<!--TIPS-->
<!--You may remove all ID or Class names which contain "demo-", they are only used for demonstration. -->

<body>

    {% block content-container %}
        put your page content here
    {% endblock %}
	<!--JAVASCRIPT-->
	<!--=================================================-->

	<!--jQuery [ REQUIRED ]-->
	<script src="/static/js/jquery-2.1.1.min.js"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="/static/js/bootstrap.min.js"></script>


	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="/static/js/nifty.min.js"></script>


    <script>
        $(document).ready(function(){

            var active_ele = $(".nano-content a[href='{{ request.path }}']");
            console.log(active_ele);
            $(active_ele).parent().addClass("active-link");
            if ($(active_ele).parent().parent().hasClass("collapse")){
                $(active_ele).parent().parent().addClass("in");
            }

        });//end doc ready

    </script>
    {% block bottom-js %}

    {% endblock %}
</body>
</html>

templates/monitor/dashboard.html
{% extends 'monitor/index.html' %}

{% block  page-title %}

    监控大盘
{% endblock %}

templates/monitor/host_groups.html
{% extends 'monitor/index.html' %}

{% block  page-title %}

    主机组
{% endblock %}

{% block breadcrumb%}
<ol class="breadcrumb">
    <li><a href="{% url 'dashboard' %}">Home</a></li>
    <li class="active">主机组</li>
</ol>
{% endblock %}

{% block page-content %}

  <div class="row">
    {% for group in host_groups %}
    <div class="col-lg-6">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">{{ group.name }}</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>主机数</td>
                            <td>服务数</td>
                            <td>已触发事件</td>
                            <td>Diaster</td>
                            <td>High</td>
                            <td>Average</td>
                            <td>Warning</td>
                            <td>Info</td>
                            <td>最后更新</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ group.host_set.all.count }}</td>
                        </tr>
                    </tbody>
                 </table>
                </div>

            </div>


        </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

    {% endfor %}
  </div>

{% endblock %}

{% block bottom-js %}
<script>

function GetHostGroupStatus() {
    /*获取每个组的主机数、服务数及状态情况*/

    $.getJSON("{% url 'get_hostgroups_status' %}",function(callback){
        console.log(callback)

    });//end getJSON

}


$(document).ready(function () {

    GetHostGroupStatus()

})

</script>
{% endblock %}

templates/monitor/hosts.html
{% extends 'monitor/index.html' %}

{% block  page-title %}

    已监控主机列表
{% endblock %}

{% block breadcrumb%}
<ol class="breadcrumb">
    <li><a href="{% url 'dashboard' %}">Home</a></li>
    <li class="active">主机列表</li>
</ol>
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">主机状态</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>主机</td>
                            <td>监控服务</td>
                            <td>状态</td>
                            <td>Up time</td>
                            <td>Diaster</td>
                            <td>High</td>
                            <td>Average</td>
                            <td>Warning</td>
                            <td>Info</td>
                            <td>最后更新</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for host in host_list %}
                        <tr host-id="{{ host.id }}">
                            <td data-type="name"><a class="btn-link" href="{% url 'host_detail' host.id %}" > {{ host.name }}({{ host.ip_addr }}) </a> </td>
                            <td data-type="services">{{ host.get_status_display }}</td>
                            <td data-type="status">{{ host.get_status_display }}</td>
                            <td data-type="uptime">loading...</td>
                            <td    onmouseover="ShowTriggerDetail({{ host.id }}, 5)" data-type="5" >

                            </td>
                            <td onmouseover="ShowTriggerDetail({{ host.id }}, 4)" data-type="4">2
                                <a href="#" class="add-popover" data-original-title="Bootstrap Popover" data-content="content" data-placement="bottom" data-trigger="focus" data-toggle="popover">Dismissible popover</a>

                            </td>
                            <td onmouseover="ShowTriggerDetail({{ host.id }}, 3)" data-type="3" ></td>
                            <td onmouseover="ShowTriggerDetail({{ host.id }}, 2)" data-type="2"></td>
                            <td onmouseover="ShowTriggerDetail({{ host.id }}, 1)" data-type="1"></td>
                            <td data-type="last_update">loading...</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>

            </div>


        </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

  </div>

{% endblock %}

{% block bottom-js %}
<script>


    TriggersData = {};//全局变量,用户在页面上看trigger详细时从这个变量里取数据

    $(document).ready(function(){
        GetHostStatus();
        var refresh_hoststatus = setInterval(function(){
            GetHostStatus();
        },10000);
    });//end doc ready
    function ShowTriggerDetail(host_id, severity){
        //console.log(host_id,severity);
        var triggers = TriggersData[host_id]['triggers'][severity];
        console.log(TriggersData[host_id]);
        if (triggers.length >0){
            console.log(triggers);
            var detail_html = "<table class='table  table-condensed'> <thead><tr> <td>Time</td><td>问题</td><td>持续时间</td><td>确认</td><td>动作</td> </tr> </thead>" +
                    "<tbody>";
            for (index in triggers){
                var tr = "<tr><td>" +triggers[index].time + "</td><td>" + triggers[index].msg +"</td><td> " + triggers[index].duration +"</td><td>" + "知道了" +"</td><td>action</td></tr>" ;
                detail_html +=tr ;
            }
            detail_html += "</tbody></table>"
            $.niftyNoty({
                type: "danger",
                container : "floating",
                title : "报警信息",
                message : detail_html,
                closeBtn : true,
                timer : 15000,
            });

        }

    }


    function GetHostStatus(){
        $.getJSON("{% url 'get_hosts_status' %}",function(callback){
            //console.log(callback);

            $.each(callback,function(index,host_obj){
                //console.log(host_obj);
                var host_html_ele  = $("#host_status_list tr[host-id='"+ host_obj.id +"']");
                //console.log(host_html_ele);
                GetStatusStyle(host_html_ele,host_obj.status);
                $(host_html_ele).find("td[data-type='uptime']").text(host_obj.uptime);
                $(host_html_ele).find("td[data-type='last_update']").text(host_obj.last_update);

                //$(host_html_ele).find("td[data-type='5'] ").text(host_obj.triggers[5].length);

                //$(host_html_ele).find("td[data-type='4'] ").text(host_obj.triggers[4].length);
                UpdateHostSeverity( $(host_html_ele).find("td[data-type='5'] "), host_obj.triggers[5]);
                UpdateHostSeverity( $(host_html_ele).find("td[data-type='4'] "), host_obj.triggers[4]);
                UpdateHostSeverity( $(host_html_ele).find("td[data-type='3'] "), host_obj.triggers[3]);
                UpdateHostSeverity( $(host_html_ele).find("td[data-type='2'] "), host_obj.triggers[2]);
                UpdateHostSeverity( $(host_html_ele).find("td[data-type='1'] "), host_obj.triggers[1]);
                //$(host_html_ele).find("td[data-type='3']").text(host_obj.triggers[3].length);
                //$(host_html_ele).find("td[data-type='2']").text(host_obj.triggers[2].length);
                //$(host_html_ele).find("td[data-type='1']").text(host_obj.triggers[1].length);

                //AddTriggerDetailIntoModel($(host_html_ele).find("td[data-type='4'] "),host_obj.triggers[4]);
                TriggersData[host_obj.id] = host_obj;
            });//end each

        })
    }

    function UpdateHostSeverity(ele,severity_data){
        ele.text(severity_data.length);
        if (severity_data.length >0){
            ele.attr('class','btn-danger');
        }else {
            ele.attr('class','');
        }
    }

    function GetStatusStyle(host_html_ele,status){
        $(host_html_ele).find("td[data-type='status']").text(status);

        var status_dic ={
            'Online':'alert-success',
            'Down':'alert-danger',
            'Unreachable':'alert-danger',
            'Offline':'alert-default',
            'Problem':'alert-warning',
        }
        var status_class = status_dic[status];
        $(host_html_ele).find("td[data-type='status']").attr('class',status_class);
    }
</script>
{% endblock %}

templates/monitor/trigger_list.html
{% load custom_tags %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Hover rows</h3>
            </div>

            <!--Hover Rows-->
            <!--===================================================-->
            <div class="panel-body">
            {{ trigger_list }}
                <table class="table table-hover table-vcenter">
                    <thead>
                        <tr>
                            <th >事件类型</th>
                            <th class="text-center">级别</th>
                            <th class="text-center">内容</th>
                            <th class="text-center">日期</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for alert in alert_list %}
                        <tr>
                            <td>{{ alert.get_event_type_display }}</td>
                            <td style="background-color: {% get_trigger_severity_color alert %}">{{ alert.trigger }}</td>
                            <td>{{ alert.log }}</td>
                            <td>{{ alert.date }}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--===================================================-->
            <!--End Hover Rows-->

        </div>
    </div>
</div>

templates/monitor/triggers.html
{% extends 'monitor/index.html' %}

{% block  page-title %}

    触发器
{% endblock %}